---
# `font` is the folder containing the fonts to test.
font: examples/fonts/Fira-Sans

# `output` is the path to the output PDF.
output: examples/output.pdf

# `defaults` is a dictionary of default values for the rules.
# Each rule can override these values in their args.
defaults:
  # `width` is the width of the output PDF in mm.
  width: 210

  # `height` is the height of the output PDF in mm.
  height: 297

  # `size` is the size of the text in pt.
  size: 30

  # `features` is a comma-separated list of OpenType features.
  # Use `none` to disable all features.
  # See https://en.wikipedia.org/wiki/List_of_typographic_features
  features: none

  # `columns` is the number of columns in the grid.
  # It pertains only to the `grid` rule.
  columns: 3

# `rules` is a list of rules to apply to the output PDF.
rules:

  # `text` writes the given text in each available font.
  - type: text

    # `args` is a dictionary of arguments to pass to the rule.
    # They override the default values defined above.
    args:
      features: zero, smcp
      size: 40

    # `inputs` is a list of strings to write in the PDF.
    # Each string is written in each available font.
    inputs:
      - testing 3.14 ff ll ii 0O

  # `grid` create a grid of all available characters in each available font.
  # It will scale down the text to fit the grid in the PDF.
  - type: grid
    # `inputs` is a list of strings to write as a grid in the PDF.
    # Each string is written in each available font.
    inputs:
      - 0
      - a
      - b
      - c
      - d

  # Examples:

  - type: text
    inputs:
      - a b c d e f g h i j k l m n o p q r s t u v w x y z
      - Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      - The quick brown fox jumps over a lazy dog.
      - Voix ambiguë d’un cœur qui au zéphyr préfère les jattes de kiwis.
      - Victor jagt zwölf Boxkämpfer quer über den großen Sylter Deich.
      - Pchnąć w tę łódź jeża lub ośm skrzyń fig.

      # Write paragraphs with a pipe `|` at the end of the line.
      - |
        Lorem ipsum odor amet, consectetuer adipiscing elit. Neque montes nam
        lorem class fringilla integer lacus pellentesque enim. Integer metus
        integer tristique class ad montes. Maximus elit vitae lacus ac vel
        hendrerit tristique. Blandit suscipit id non aliquet proin. Mattis
        senectus magnis suscipit habitant a at commodo fusce. Eget dictumst dis
        feugiat fermentum rutrum mollis mattis massa. Natoque non nostra
        curabitur malesuada magna ligula.

  - type: grid
    args:
      size: 100
      columns: 2
      features: smcp, subs
    inputs:
      - 012
      - abc
      - éèêë
      - çùûü
