font: ./fonts/Fira-Sans
output: ./output.pdf

rules:
  - type: text
    features: "sups"
    args:
      - "testing 3.14 ff ll ii 0O"
  - type: alphabet
  - type: grid
    args:
      - 01a
  - type: grid
    features: "zero, smcp"
    args:
      - 01a
  - type: text
    args:
      - "Hello, world!"
